### ISSUE TITLE
Slight changes needed for new swift version

### ISSUE THREAD

**Issue by rougegoat** [jason-tratta/SwiftJSS#1]
Just downloaded this to poke around a bit with Swift and the JSS.  I had to convert things to newer versions.  The automated conversion hit most things, but it didn't quite fix everything.  Lines 130 and 135 in JSSComunicationClient.swift throw errors when you try to build it.  It seems to work when you change it from 

```
challenge.sender.useCredential(newCredential, forAuthenticationChallenge: challenge)
```

to

```
challenge.sender!.useCredential(newCredential, forAuthenticationChallenge: challenge)
```

and line 135 in pretty much the exact same way, everything builds just fine but with some warnings.  I think the only other major changes the automated tool applied where things like changing print to println.

**Comment by jason-tratta** [comment]
Whoops. Changing my last comment.  Yes...I need to update this to the newest swift version.  Are you using Xcode 7.0?

**Comment by rougegoat** [comment]
XCode 7.0.1.

**Comment by jason-tratta** [comment]
OK. Should now work with the current Xcode. The only warnings should be warnings about un-used variables.   Thanks for the heads up!
